#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""doc_sync.py — Gate 7 (Doc Sync) writing-layer drift guard (#446).

Issue #446 G-class: the gate count lives in ONE place (the GATES registry
in quality_gates.py) but was COPIED into docstrings, hook headers, README
tables, and CI workflow comments — every copy a drift seed. The 7th live
drift (issue comment 2026-08-19): references/_INDEX.md edited without
re-pinning references/_INDEX.yaml, failing a test AFTER landing. This gate
makes both failure classes mechanical at commit time.

Three sub-checks were shipped by #446 (design.md D2-D5, (a)-(c) below);
#476 added the ext-index consistency sub-check (d).
  (a) gate-count claim scan — any numeric count claim about gates
      ("N-gate", "N gates", "N 个 Gate", "N 门") on the devkit/** +
      .github/workflows/** face is a violation. Number-free wording is
      the fix: the registry is the count's only source. Deliberately NOT
      "number != len(GATES)" — even a currently-correct number goes stale
      when the next gate registers (derive-don't-copy). Face scope is
      empirical: scripts/hooks/tests talk about a DIFFERENT gate family
      (product enforcement gates, version ids, DIFF-N ids); scanning them
      would be noise, not signal.
  (b) references re-pin — staged references/*.md (non-archive) requires a
      staged references/_INDEX.yaml whose files: pins match the STAGED
      content sha256 (git show :path — catches both "yaml not staged" and
      "yaml staged but stale"). Violation → HARD_PAUSE; fix is
      `uv run python scripts/re_pin_references.py` + stage the yaml.
  (c) mechanism registration ledger — staged NEW scripts/*.py
      (--diff-filter=A) whose stem is not mentioned in
      references/_INDEX.md → WARN (non-blocking): a new mechanism
      registers three pieces (code + reference + index row). Existing
      unregistered scripts are pre-existing debt, never retroactive
      failures.
  (d) ext index consistency (#476) — tools/_INDEX.ext.yaml (the
      describe-only capability catalog generated by tools/ext-scan.py)
      is read from the WORKING tree (the same copy the query face
      reads): an entry with a dangling source path, missing
      name/capability/source, or a name colliding with an internal
      registered name → FAIL; an entry-point scripts/ or hooks/ file
      absent from the catalog → WARN (fix: regenerate via
      tools/ext-scan.py — the shipped catalog is exhaustive, so any gap
      is drift, not pre-existing debt).

Exit codes: 0 = pass; 1 = violations found; 2 = HARD_PAUSE (references
unpinned). Registered as Gate 7 in quality_gates.GATES; the pre-commit
template runs it in its quick set. Fail-closed on unexpected exceptions
is provided by the quality_gates runner wrapper (same as Gates 5/6).
"""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

# #863 Family B: reach the canonical by-path loader in hooks/. devkit is its
# own sys.path domain, so bridge once here — guarded APPEND (never insert(0):
# reordering hooks/ ahead of scripts/ is the #671 shared-name-twin shadow).
_HOOKS_DIR = str(Path(__file__).resolve().parent.parent / "hooks")
if _HOOKS_DIR not in sys.path:
    sys.path.append(_HOOKS_DIR)
from _path_hygiene import load_module_by_path  # noqa: E402  (#671 authority)

REPO_ROOT = Path(__file__).resolve().parent.parent

# Scan face: the quality-gate family's documentation carriers only.
SCAN_ROOTS = ("devkit", ".github/workflows")

_SKIP_DIRS = {"__pycache__", ".git"}

# Numeric gate-count claim: digit(s), optional Chinese counter 个,
# optional spaces, then a hyphen+gate(s) / space+gate(s) / 门, with an
# optional "quality" qualifier (the CJK form with 个). Single-gate IDs
# ("Gate 5", "Gate 1 + 3") and CLI arg lists never match because the
# digit must PRECEDE the gate word. (Wording here stays number-free on
# purpose: this file is inside its own scan face.)
_COUNT_CLAIM_RE = re.compile(
    r"(?<![0-9A-Za-z])\d{1,2}(?:[ \t]*个)?[ \t]*-[ \t]*(?:quality[ \t]+)?gates?\b"
    r"|(?<![0-9A-Za-z])\d{1,2}(?:[ \t]*个)?[ \t]+(?:quality[ \t]+)?gates?\b"
    r"|(?<![0-9A-Za-z])\d{1,2}(?:[ \t]*个)?[ \t]*(?:quality[ \t]+)?门",
    re.IGNORECASE)

RC_PASS = 0
RC_FAIL = 1
RC_PAUSE = 2

INDEX_YAML = "references/_INDEX.yaml"
INDEX_MD = "references/_INDEX.md"


def _out_encoding() -> str:
    return getattr(sys.stdout, "encoding", None) or "utf-8"


def _safe(text: str) -> str:
    """GBK-console safety (2026-08-20 lesson): violations carry CJK text;
    printing raw crashed a scan on a GBK Windows console."""
    enc = _out_encoding()
    return text.encode(enc, "replace").decode(enc, "replace")


def _staged_files(extra_args: list[str] | None = None) -> list[str]:
    """Staged (cached) file paths relative to repo root. Git failure →
    empty list (N/A semantics, mirrors subagent_review._staged_files)."""
    cmd = ["git", "diff", "--cached", "--name-only"]
    if extra_args:
        cmd += extra_args
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO_ROOT,
                       errors="replace")
    if r.returncode != 0:
        return []
    return [ln.strip() for ln in r.stdout.splitlines() if ln.strip()]


def _staged_bytes(rel: str) -> bytes | None:
    """Staged (index) content of one file; None when not staged/readable."""
    r = subprocess.run(["git", "show", f":{rel}"], capture_output=True,
                       cwd=REPO_ROOT)
    return r.stdout if r.returncode == 0 else None


def _parse_pins(yaml_text: str) -> dict[str, str]:
    """Parse the files: block of references/_INDEX.yaml (line-level, the
    same parse re_pin_references.py performs — no yaml dependency in
    devkit, which is stdlib-only by convention)."""
    pins: dict[str, str] = {}
    in_files = False
    for ln in yaml_text.splitlines():
        if ln.strip() == "files:":
            in_files = True
            continue
        if in_files:
            if ln.startswith("  ") and ":" in ln:
                path, _, sha = ln.strip().rpartition(":")
                pins[path.strip()] = sha.strip()
            else:
                in_files = False
    return pins


def _iter_face_files() -> list[Path]:
    out: list[Path] = []
    for root_rel in SCAN_ROOTS:
        root = REPO_ROOT / root_rel
        if not root.is_dir():
            continue
        for p in sorted(root.rglob("*")):
            if not p.is_file():
                continue
            if _SKIP_DIRS.intersection(p.parts):
                continue
            out.append(p)
    return out


def scan_gate_count_claims() -> list[dict]:
    """Return every numeric gate-count claim on the scan face as
    {"file", "line", "text", "claim"} (file is repo-relative POSIX)."""
    claims: list[dict] = []
    for p in _iter_face_files():
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if "\x00" in text:  # binary-ish — not prose, skip
            continue
        for i, ln in enumerate(text.splitlines(), 1):
            m = _COUNT_CLAIM_RE.search(ln)
            if m:
                claims.append({
                    "file": p.relative_to(REPO_ROOT).as_posix(),
                    "line": i,
                    "text": ln.strip()[:120],
                    "claim": m.group(0),
                })
    return claims


def _check_references_pins() -> list[str]:
    """Sub-check (b). Returns HARD_PAUSE reasons (empty = ok / N/A)."""
    staged = _staged_files()
    ref_md = [p for p in staged
              if p.startswith("references/") and p.endswith(".md")
              and "archive/" not in p]
    if not ref_md:
        return []
    if INDEX_YAML not in staged:
        return [
            f"{', '.join(ref_md)}: staged without {INDEX_YAML} — "
            "references edits must re-pin in the same commit "
            "(uv run python scripts/re_pin_references.py, then stage the yaml)"
        ]
    yaml_bytes = _staged_bytes(INDEX_YAML)
    if yaml_bytes is None:
        return [f"{INDEX_YAML}: staged but unreadable from the index"]
    pins = _parse_pins(yaml_bytes.decode("utf-8", errors="replace"))
    pauses: list[str] = []
    for rel in ref_md:
        if rel not in pins:
            pauses.append(f"{rel}: no pin in staged {INDEX_YAML} "
                          "(new references file — re-pin required)")
            continue
        data = _staged_bytes(rel)
        if data is None:
            pauses.append(f"{rel}: staged list says staged, index read failed")
            continue
        actual = hashlib.sha256(data).hexdigest()
        if actual != pins[rel]:
            pauses.append(
                f"{rel}: staged sha {actual[:12]} != staged pin "
                f"{pins[rel][:12]} — pin is stale, re-run "
                "scripts/re_pin_references.py")
    return pauses


def _check_new_script_registration() -> list[str]:
    """Sub-check (c). Returns WARN strings (never blocking, design D5)."""
    added = _staged_files(["--diff-filter=A"])
    new_scripts = [p for p in added
                   if p.startswith("scripts/") and p.endswith(".py")]
    if not new_scripts:
        return []
    idx = REPO_ROOT / INDEX_MD
    try:
        idx_text = idx.read_text(encoding="utf-8", errors="replace")
    except OSError:
        idx_text = ""
    warns: list[str] = []
    for rel in new_scripts:
        stem = Path(rel).stem
        if stem not in idx_text:
            warns.append(
                f"{rel}: stem {stem!r} is not mentioned in {INDEX_MD} — "
                "a new mechanism registers three pieces (code + reference "
                "+ index row); pre-existing unregistered scripts are "
                "existing debt, not a failure")
    return warns


def _registry_note() -> str:
    """Guidance text only — the registry len is NOT part of the verdict
    (design D3: judgement is number-free, so it cannot drift)."""
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        import quality_gates as _qg
        return (f"gate count is registry-derived "
                f"(devkit/quality_gates.py GATES: {len(_qg.GATES)} registered)")
    except Exception:
        return "gate count is registry-derived (devkit/quality_gates.py GATES)"


# ---- sub-check (d): ext index consistency (#476) -------------------------

EXT_INDEX_REL = "tools/_INDEX.ext.yaml"
INTERNAL_INDEX_REL = "tools/_INDEX.yaml"

# #515: environment-side entries (name mcp__<server>, merged via
# `tools/ext-scan.py --with-mcp`) describe a machine-local MCP
# registration, not a repo file — their existence semantics degrades to
# SANCTIONED-PROVENANCE checking: source must be one of these labels and
# the name must match the canonical mcp server shape. The generating
# machine's claude-json path is neither portable nor verifiable from the
# repo, so a raw path in that slot is a FAIL, not a pass.
ENV_PROVENANCE_SOURCES = ("claude-json",)
MCP_NAME_RE_STR = r"^mcp__[a-z0-9][a-z0-9_-]*$"

_EXT_SCAN_CACHE: dict[str, object] = {}


def _scalar(value: str) -> str:
    """Strip a yaml scalar: surrounding double quotes (json-escaped by
    the generator) or raw text."""
    v = value.strip()
    if v.startswith('"') and v.endswith('"') and len(v) >= 2:
        try:
            loaded = json.loads(v)
            return loaded if isinstance(loaded, str) else v
        except ValueError:
            return v
    return v


def _parse_named_list(text: str, list_key: str) -> list[dict] | None:
    """Line-level parse of a `<list_key>:` block of `- name:`-headed
    entries (stdlib-only, same convention as _parse_pins). Returns None
    when the key is absent (not an index of that shape)."""
    entries: list[dict] = []
    cur: dict | None = None
    in_list = False
    for ln in text.splitlines():
        if ln.startswith(f"{list_key}:"):
            in_list = True
            continue
        if not in_list:
            continue
        if ln.startswith("  - name:"):
            if cur is not None:
                entries.append(cur)
            cur = {"name": _scalar(ln.partition(":")[2])}
        elif cur is not None and ln.startswith("    ") and ":" in ln:
            k, _, v = ln.strip().partition(":")
            cur[k.strip()] = _scalar(v)
        elif ln.strip() and not ln.startswith((" ", "#")):
            if cur is not None:
                entries.append(cur)
            cur = None
            in_list = False
    if cur is not None:
        entries.append(cur)
    return None if not in_list else entries


def _internal_registered_names() -> set[str]:
    """Internal tools/_INDEX.yaml registered names (line-level)."""
    ipath = REPO_ROOT / INTERNAL_INDEX_REL
    if not ipath.is_file():
        return set()
    entries = _parse_named_list(
        ipath.read_text(encoding="utf-8", errors="replace"), "tools") or []
    return {e["name"] for e in entries if e.get("name")}


def _load_ext_scan():
    """Import tools/ext-scan.py (hyphenated meta-tool filename →
    importlib file-location load). Cached; None when unavailable — the
    WARN side degrades to silence, the FAIL side never depends on it.
    #863 Family B: the load itself delegates to the canonical loader
    (hooks/_path_hygiene.load_module_by_path); the local dict keeps the
    None-caching semantics (util caches successes via sys.modules)."""
    if "mod" in _EXT_SCAN_CACHE:
        return _EXT_SCAN_CACHE["mod"]
    path = Path(__file__).resolve().parent.parent / "tools" / "ext-scan.py"
    mod = None
    try:
        mod = load_module_by_path("kunglao_ext_scan", path)
    except Exception:  # noqa: BLE001 - generator import is best-effort
        mod = None
    _EXT_SCAN_CACHE["mod"] = mod
    return mod


def _check_ext_index() -> tuple[list[str], list[str]]:
    """Sub-check (d). Returns (fails, warns) — fails map to RC_FAIL,
    warns are non-blocking (same shape as the #446 sub-check family)."""
    ext_path = REPO_ROOT / EXT_INDEX_REL
    if not ext_path.is_file():
        return [], []  # N/A: existence is pinned by tests, not ransomed here
    text = ext_path.read_text(encoding="utf-8", errors="replace")
    entries = _parse_named_list(text, "ext")
    fails: list[str] = []
    warns: list[str] = []
    if entries is None:
        return [f"{EXT_INDEX_REL}: no 'ext:' list — regenerate via "
                f"`uv run python tools/ext-scan.py`"], warns

    names: set[str] = set()
    internal = _internal_registered_names()
    for i, e in enumerate(entries):
        loc = f"{EXT_INDEX_REL} ext[{i}]"
        name = str(e.get("name", "")).strip()
        if not name:
            fails.append(f"{loc}: missing/empty 'name'")
            continue
        if name in names:
            fails.append(f"{loc}: duplicate name '{name}'")
        names.add(name)
        for field in ("capability", "source"):
            if not str(e.get(field, "")).strip():
                fails.append(f"{loc} ({name}): missing/empty '{field}'")
        source = str(e.get("source", "")).strip()
        if name.startswith("mcp__"):
            # #515 environment entry: provenance semantics, not repo-path
            # existence (the check must be name-shape-first so a malformed
            # server name can never ride a sanctioned label through).
            if not re.match(MCP_NAME_RE_STR, name):
                fails.append(
                    f"{loc} ({name}): environment entry name must match "
                    f"{MCP_NAME_RE_STR} (canonical lowercase mcp server)")
            elif source not in ENV_PROVENANCE_SOURCES:
                fails.append(
                    f"{loc} ({name}): environment entry source {source!r} "
                    f"is not a sanctioned provenance label "
                    f"{list(ENV_PROVENANCE_SOURCES)} — regenerate via "
                    f"`uv run python tools/ext-scan.py --with-mcp "
                    f"<probe.json>` (#515)")
        elif source and not (REPO_ROOT / source).exists():
            fails.append(
                f"{loc} ({name}): source '{source}' does not exist — "
                "regenerate via `uv run python tools/ext-scan.py` "
                "(dangling catalog entry)")
        if name in internal:
            fails.append(
                f"{loc} ({name}): collides with an internal "
                f"{INTERNAL_INDEX_REL} registered name — bare-name "
                "resolution must stay unambiguous")

    ext_scan = _load_ext_scan()
    if ext_scan is None:
        return fails, warns
    for rel, _kind in ext_scan.iter_entry_sources(REPO_ROOT):  # type: ignore[attr-defined]
        stem = Path(rel).stem
        if not set(ext_scan.indexed_name_candidates(stem)) & names:  # type: ignore[attr-defined]
            warns.append(
                f"{rel}: entry-point file not in {EXT_INDEX_REL} — the "
                "catalog drifted; regenerate via "
                "`uv run python tools/ext-scan.py` (#476)")
    return fails, warns


def check() -> int:
    claims = scan_gate_count_claims()
    pauses = _check_references_pins()
    warns = _check_new_script_registration()
    ext_fails, ext_warns = _check_ext_index()
    warns = warns + ext_warns

    for w in warns:
        print(_safe(f"  [WARN] {w}"))

    if pauses:
        print(_safe(f"HARD_PAUSE Gate 7: {len(pauses)} references re-pin "
                    f"violation(s):"))
        for p in pauses:
            print(_safe(f"  {p}"))
        print(_safe("  Fix: uv run python scripts/re_pin_references.py, "
                    "then git add references/_INDEX.yaml"))
        return RC_PAUSE

    if ext_fails:
        print(_safe(f"FAIL Gate 7: {len(ext_fails)} ext index "
                    f"inconsistency (working-tree {EXT_INDEX_REL}):"))
        for f in ext_fails:
            print(_safe(f"  {f}"))
        print(_safe("  Fix: uv run python tools/ext-scan.py, then commit "
                    f"the regenerated {EXT_INDEX_REL}"))
        return RC_FAIL

    if claims:
        print(_safe(f"FAIL Gate 7: {len(claims)} numeric gate-count "
                    f"claim(s) on the devkit/workflows face "
                    f"({_registry_note()}):"))
        for c in claims:
            print(_safe(f"  {c['file']}:{c['line']}: claim {c['claim']!r} "
                        f"— {c['text']}"))
        print(_safe("  Fix: number-free wording (the GATES registry is the "
                    "count's only source); claims are violations even when "
                    "the number is currently correct"))
        return RC_FAIL

    print("[PASS] Gate 7 doc sync: gate-count claim scan clean, "
          "references pins clean, ext index consistent"
          + (f", {len(warns)} registration WARN(s)" if warns else ""))
    return RC_PASS


def main(argv: list[str] | None = None) -> int:
    return check()


if __name__ == "__main__":
    sys.exit(main())
