# -*- coding: utf-8 -*-
"""Issue #278 — scripts/template_gen.py: deterministic script-template generation (TDD).

Templateization half of #278 (absorption half is blocked on the Windows host).

Acceptance:
  (a) generate stage-unpack with all required params -> file exists, values
      substituted, NO "{{" placeholder leftovers;
  (b) unknown template -> exit 2;
  (c) missing required param -> exit 3 + missing names on stderr;
  (d) existing target without --force -> exit 4, file untouched; with
      --force -> overwritten;
  (e) determinism: same params + different out dirs -> body byte-identical,
      header differs only in the timestamp;
  (f) every generated script passes `py_compile` (syntactically valid Python).
  Plus: leftover-placeholder template defect -> exit 5 (fail-closed); bad
  --name / malformed --param -> exit 2 (usage).
"""
from __future__ import annotations

import py_compile
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / "scripts" / "template_gen.py"

# Single source for param values + assertions (#690: relative, no literal
# duplication — expected values derive from the same constants).
SAMPLE = "samples/p1.bin"
STAGE_OUT = "work/p1/stages"
PLAIN_OUT = "work/p1/plain"
DISASM_OUT = "work/p1/disasm"

STAGE_PARAMS = [
    "--param", f"sample_path={SAMPLE}",
    "--param", "sample_sha256=" + "ab" * 32,
    "--param", "offsets=0x1a00,0x3c40",
    "--param", "stage_names=stage1,stage2",
    "--param", f"output_dir={STAGE_OUT}",
]

DECRYPT_PARAMS = [
    "--param", f"sample_path={SAMPLE}",
    "--param", "sample_sha256=" + "ab" * 32,
    "--param", "decrypt_offset=0x403010",
    "--param", "key_va=0x405000",
    "--param", f"output_dir={PLAIN_OUT}",
]

DISASM_PARAMS = [
    "--param", f"sample_path={SAMPLE}",
    "--param", "sample_sha256=" + "ab" * 32,
    "--param", "entry_points=0x401000,0x401020",
    "--param", f"output_dir={DISASM_OUT}",
]

# Each template -> (default name, full required params).
ALL_CASES = [
    ("stage-unpack", "p1-unpack", STAGE_PARAMS),
    ("decryption-analysis", "p1-decrypt", DECRYPT_PARAMS),
    ("disasm-pipeline", "p1-disasm", DISASM_PARAMS),
]


def _run(tmp_path: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(GEN), *args],
        cwd=ROOT, capture_output=True, text=True, timeout=60,
        encoding="utf-8", errors="replace",
    )


# ---------- (a) happy path: substitution + no leftovers ----------

def test_generate_stage_unpack_substitutes_and_no_leftovers(tmp_path: Path) -> None:
    """All required params land in the file; no {{...}} placeholder survives."""
    out = tmp_path / "gen"
    r = _run(tmp_path, "--template", "stage-unpack", "--name", "p1-unpack",
             "--out", str(out), *STAGE_PARAMS)
    assert r.returncode == 0, f"rc={r.returncode} err={r.stderr}"
    target = out / "p1-unpack.py"
    assert target.is_file()
    text = target.read_text(encoding="utf-8")
    assert SAMPLE in text
    assert "ab" * 32 in text
    assert "0x1a00,0x3c40" in text
    assert "stage1,stage2" in text
    assert STAGE_OUT in text
    assert "{{" not in text
    assert text.startswith("# generated by template_gen.py from stage-unpack on ")


# ---------- (b) unknown template ----------

def test_unknown_template_exit_2(tmp_path: Path) -> None:
    """Unknown template name -> exit 2 (argparse choice rejection)."""
    r = _run(tmp_path, "--template", "no-such-template", "--name", "x",
             "--out", str(tmp_path / "o"))
    assert r.returncode == 2
    assert "no-such-template" in r.stderr


# ---------- (c) missing required params ----------

def test_missing_required_params_exit_3_lists_names(tmp_path: Path) -> None:
    """Only some params supplied -> exit 3, missing names on stderr."""
    r = _run(tmp_path, "--template", "stage-unpack", "--name", "x",
             "--out", str(tmp_path / "o"),
             "--param", "sample_path=foo",
             "--param", "sample_sha256=bar",
             "--param", "offsets=0x1a00",
             "--param", "stage_names=s1")  # output_dir missing
    assert r.returncode == 3
    assert "output_dir" in r.stderr


def test_missing_multiple_required_params_all_listed(tmp_path: Path) -> None:
    """Every missing required param is named, not just the first."""
    r = _run(tmp_path, "--template", "decryption-analysis", "--name", "x",
             "--out", str(tmp_path / "o"),
             "--param", "sample_path=foo")  # 4 others missing
    assert r.returncode == 3
    for name in ("sample_sha256", "decrypt_offset", "key_va", "output_dir"):
        assert name in r.stderr
    assert "sample_path" not in r.stderr  # the supplied param is not "missing"


# ---------- (d) existing target: refuse without --force ----------

def test_existing_target_requires_force(tmp_path: Path) -> None:
    """Rerun without --force -> exit 4 and file untouched; with --force -> overwritten."""
    out = tmp_path / "gen"
    args = ("--template", "stage-unpack", "--name", "p1-unpack",
            "--out", str(out), *STAGE_PARAMS)
    assert _run(tmp_path, *args).returncode == 0
    first = (out / "p1-unpack.py").read_text(encoding="utf-8")

    r = _run(tmp_path, *args)
    assert r.returncode == 4, f"rc={r.returncode} err={r.stderr}"
    assert (out / "p1-unpack.py").read_text(encoding="utf-8") == first  # untouched

    r = _run(tmp_path, *args, "--force")
    assert r.returncode == 0, f"rc={r.returncode} err={r.stderr}"
    second = (out / "p1-unpack.py").read_text(encoding="utf-8")
    assert second.split("\n", 1)[1] == first.split("\n", 1)[1]  # body preserved


# ---------- (e) determinism ----------

def test_deterministic_body_modulo_timestamp_header(tmp_path: Path) -> None:
    """Same params + different out dirs -> byte-identical body; header lines
    carry the provenance + timestamp and differ from each other only in ts."""
    out1 = tmp_path / "a"
    out2 = tmp_path / "b"
    r1 = _run(tmp_path, "--template", "stage-unpack", "--name", "p1-unpack",
              "--out", str(out1), *STAGE_PARAMS)
    r2 = _run(tmp_path, "--template", "stage-unpack", "--name", "p1-unpack",
              "--out", str(out2), *STAGE_PARAMS)
    assert r1.returncode == 0 and r2.returncode == 0
    t1 = (out1 / "p1-unpack.py").read_text(encoding="utf-8")
    t2 = (out2 / "p1-unpack.py").read_text(encoding="utf-8")
    h1, b1 = t1.split("\n", 1)
    h2, b2 = t2.split("\n", 1)
    assert b1 == b2
    assert h1.startswith("# generated by template_gen.py from stage-unpack on ")
    assert h2.startswith("# generated by template_gen.py from stage-unpack on ")
    # NOTE: h1 == h2 is legal when both runs land in the same second; the
    # determinism contract is that the header is the ONLY variable part.


# ---------- (f) generated scripts are valid Python ----------

def test_all_generated_scripts_compile(tmp_path: Path) -> None:
    """Every template generates syntactically valid Python (py_compile)."""
    for template, name, params in ALL_CASES:
        out = tmp_path / template
        r = _run(tmp_path, "--template", template, "--name", name,
                 "--out", str(out), *params)
        assert r.returncode == 0, f"{template}: rc={r.returncode} err={r.stderr}"
        target = out / f"{name}.py"
        py_compile.compile(str(target), doraise=True)
        text = target.read_text(encoding="utf-8")
        assert "{{" not in text, f"{template}: placeholder leaked"


# ---------- fail-closed template defect + usage guards ----------

def test_leftover_placeholder_is_template_defect_exit_5(tmp_path: Path) -> None:
    """A template whose placeholders are not covered by supplied params is a
    template defect: fail closed with exit 5 listing the leftover keys."""
    tdir = tmp_path / "tmpl"
    tdir.mkdir()
    (tdir / "bad.py.tmpl").write_text(
        "# placeholder below is NOT a registered required param\n"
        "VALUE = \"{{bogus_key}}\"\n",
        encoding="utf-8",
    )
    r = _run(tmp_path, "--templates-dir", str(tdir), "--template", "bad",
             "--name", "x", "--out", str(tmp_path / "o"))
    assert r.returncode == 5
    assert "bogus_key" in r.stderr


def test_name_with_path_traversal_exit_2(tmp_path: Path) -> None:
    """--name must be a plain slug; path separators / .. are usage errors."""
    r = _run(tmp_path, "--template", "stage-unpack", "--name", "../evil",
             "--out", str(tmp_path / "o"))
    assert r.returncode == 2
    assert "../evil" in r.stderr


def test_malformed_param_exit_2(tmp_path: Path) -> None:
    """--param without '=' is a usage error."""
    r = _run(tmp_path, "--template", "stage-unpack", "--name", "x",
             "--out", str(tmp_path / "o"), "--param", "sample_path")
    assert r.returncode == 2
