#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""template_gen.py — deterministic script-template generator (issue #278).

Templateization half of #278: instantiate a script template from
templates/scripts/*.tmpl with explicit parameters into a runnable analysis
script. The absorption half (inventorying + migrating the 236 field scripts
under D:\\works\\samples) is BLOCKED on the unreachable Windows host; the
classification framework the absorption pass will fill in lives in
templates/README.md.

Template catalog (name -> templates/scripts/<name>.py.tmpl):

  stage-unpack         carve stage -> sha256 -> dump
                       required: sample_path, sample_sha256, offsets,
                                 stage_names, output_dir
  decryption-analysis  locate decrypt routine -> call params -> decrypt -> hash
                       required: sample_path, sample_sha256, decrypt_offset,
                                 key_va, output_dir
  disasm-pipeline      entry points -> disasm -> xrefs -> summary
                       required: sample_path, sample_sha256, entry_points,
                                 output_dir

CLI:
  python scripts/template_gen.py --template <name> --name <slug> --out <dir>
      [--param key=value]... [--force] [--templates-dir <dir>]

Semantics:
  * every {{KEY}} placeholder in the template is replaced by the value of the
    --param KEY=... argument (verbatim, single pass; values are inserted into
    the template's quoted strings, so values with quotes/backslashes are the
    caller's responsibility);
  * the output file is <out>/<name>.py and starts with a provenance header
    (`# generated by template_gen.py from <template> on <ts>`); the header is
    the ONLY non-deterministic part — same inputs produce byte-identical
    bodies;
  * extra --param keys not present in the template are ignored; repeated keys
    last-wins; `name` is reserved — the --name slug is injected as `{{name}}`
    (a --param name= is overridden);
  * a template whose placeholders are not covered by the supplied params is a
    TEMPLATE DEFECT -> fail closed.

Exit codes: 0 = generated; 2 = usage error (unknown template, bad --name,
malformed --param); 3 = missing required param(s) (listed on stderr); 4 =
target exists without --force; 5 = template defect (leftover {{...}}).

Deterministic + stdlib only (no third-party imports).
"""
from __future__ import annotations

import argparse
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TEMPLATES_DIR = ROOT / "templates" / "scripts"

# template name -> required params (order = display/error order). This map is
# the single source of truth for the CLI contract; templates/README.md
# mirrors it for humans.
REQUIRED_PARAMS: dict[str, tuple[str, ...]] = {
    "stage-unpack": ("sample_path", "sample_sha256", "offsets", "stage_names", "output_dir"),
    "decryption-analysis": ("sample_path", "sample_sha256", "decrypt_offset", "key_va", "output_dir"),
    "disasm-pipeline": ("sample_path", "sample_sha256", "entry_points", "output_dir"),
}

_PLACEHOLDER = re.compile(r"\{\{([A-Za-z0-9_]+)\}\}")
_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
TS_FORMAT = "%Y-%m-%dT%H:%M:%SZ"

EXIT_OK = 0
EXIT_USAGE = 2
EXIT_MISSING_PARAMS = 3
EXIT_EXISTS = 4
EXIT_TEMPLATE_DEFECT = 5


def render(template_text: str, params: dict[str, str]) -> str:
    """Replace every {{KEY}} placeholder with params[KEY] (single pass,
    verbatim — substituted values are never re-scanned). Placeholders with no
    matching key are left intact so leftover_placeholders() can report them."""
    def _sub(m: re.Match[str]) -> str:
        return params.get(m.group(1), m.group(0))
    return _PLACEHOLDER.sub(_sub, template_text)


def leftover_placeholders(text: str) -> list[str]:
    """Placeholder keys still present after rendering (template defect)."""
    return sorted(set(_PLACEHOLDER.findall(text)))


def header(template: str, ts: str) -> str:
    """Provenance header — the only non-deterministic part of the output."""
    return (
        f"# generated by template_gen.py from {template} on {ts}\n"
        f"# template: templates/scripts/{template}.py.tmpl — fill the TODOs "
        "marked in the body before running.\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="template_gen.py",
        description="Deterministic script-template generator (issue #278). "
                    "Catalog: " + ", ".join(sorted(REQUIRED_PARAMS)),
        epilog="Templates live in templates/scripts/*.tmpl; required params "
               "per template are enforced (exit 3). See templates/README.md.",
    )
    parser.add_argument("--template", required=True,
                        help="template name: " + " | ".join(sorted(REQUIRED_PARAMS)))
    parser.add_argument("--name", required=True,
                        help="output file slug (no path separators); <name>.py is written")
    parser.add_argument("--out", required=True, help="output directory (created if missing)")
    parser.add_argument("--param", action="append", default=[], metavar="KEY=VALUE",
                        help="parameter to substitute into the template (repeatable)")
    parser.add_argument("--force", action="store_true",
                        help="overwrite the target file if it already exists")
    parser.add_argument("--templates-dir", default=str(DEFAULT_TEMPLATES_DIR),
                        help="directory holding <name>.py.tmpl (default: templates/scripts)")
    args = parser.parse_args(argv)

    if not _NAME_RE.match(args.name) or args.name in (".", ".."):
        print(f"ERROR invalid --name: {args.name!r} (use a plain slug)", file=sys.stderr)
        return EXIT_USAGE

    params: dict[str, str] = {}
    for item in args.param:
        key, sep, value = item.partition("=")
        if not sep:
            print(f"ERROR malformed --param (expected KEY=VALUE): {item!r}", file=sys.stderr)
            return EXIT_USAGE
        params[key] = value  # repeated keys: last wins (documented)
    params["name"] = args.name  # reserved: {{name}} -> output slug

    templates_dir = Path(args.templates_dir)
    template_file = templates_dir / f"{args.template}.py.tmpl"
    if not template_file.is_file():
        print(f"ERROR unknown template: {args.template!r} (no {template_file}); "
              f"known: {', '.join(sorted(REQUIRED_PARAMS))}", file=sys.stderr)
        return EXIT_USAGE

    missing = [k for k in REQUIRED_PARAMS.get(args.template, ()) if k not in params]
    if missing:
        print(f"ERROR missing required params for template {args.template!r}: "
              f"{', '.join(missing)}", file=sys.stderr)
        return EXIT_MISSING_PARAMS

    rendered = render(template_file.read_text(encoding="utf-8"), params)
    leftovers = leftover_placeholders(rendered)
    if leftovers:
        print(f"ERROR template defect: {args.template}.py.tmpl has placeholders "
              f"not covered by supplied params: {', '.join(leftovers)}", file=sys.stderr)
        return EXIT_TEMPLATE_DEFECT

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    target = out / f"{args.name}.py"
    if target.exists() and not args.force:
        print(f"ERROR target exists (use --force to overwrite): {target}", file=sys.stderr)
        return EXIT_EXISTS

    ts = time.strftime(TS_FORMAT, time.gmtime())
    target.write_text(header(args.template, ts) + rendered, encoding="utf-8")
    print(f"generated {target} from {args.template} (params: {', '.join(sorted(params))})")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
